### PR TITLE
Linux changes.

### PR DESCRIPTION
**Pull request by greblus**
- Use native linux versions of the tools
- Use local config file instead of user's global config 
- 32-bit static binaries of tools should work everywhere

### CODE REVIEW

**Comment by mgr-inz-rafal** [comment]
There might be still something wrong with pulling the output from Emulator.

Example output of test on Windows:

```
d:\git\tubac\tests\src\tests.cpp(282):
PASSED:
  CHECK( result.first == result.second )
with expansion:
  "1
  2"
  ==
  "1
  2"
with messages:
  10 PRINT 1
  20 PRINT 2
  30 END
  40 PRINT 3
  50 PRINT 4
  suites\end\test1.txt

```
But on Linux we see no expansion:
```
/home/prezes/Git/tubac/tests/src/tests.cpp:287: 
PASSED:
  CHECK( result.first == result.second )
with expansion:
  "" == ""
with messages:
  10 PRINT 1
  20 PRINT 2
  30 END
  40 PRINT 3
  50 PRINT 4
  suites/end/test1.txt

```
The expression "" == "" is true for every test case :)

Could you try to run:
`./tubac_tests -s`
to see all progress?

**Comment by greblus** [comment]
Ok, again flushing the buffers kicked me in the ass (I've just added a modified binary).
But now the output is strange, some (8) tests are passing, some not.
[out.txt](https://github.com/mgr-inz-rafal/tubac/files/999373/out.txt)
It looks that all tests with dos line endings are failing... Time to modify franny.

**Comment by greblus** [comment]
Looks good now. 

There is only one strange "" == "" expansion:
PASSED:
  CHECK( result.first == result.second )
with expansion:
  "" == ""
with messages:
  10 I=10:WHILE I=20:PRINT I:WEND
  suites/loop_while/simple1.txt
[out.txt](https://github.com/mgr-inz-rafal/tubac/files/999513/out.txt)

**Comment by mgr-inz-rafal** [comment]
That's OK. This test case is expected to give null output. It tests whether execution skips the loop entirely, given I is initialized with 10.

I've added PRINT 666 after WEND so it a little more clear that test has been executed.

Thanks for your changes!

PS. So now we have:
```
/home/prezes/Git/tubac/tests/src/tests.cpp:286: 
PASSED:
  CHECK( result.first == result.second )
with expansion:
  "666" == "666"
with messages:
  10 I=10:WHILE I=20:PRINT I:WEND:PRINT 666
  suites/loop_while/simple1.txt
```

**Pull request merged**
